export type Language = "en" | "zh" | "hi" | "es" | "fr" | "pt" | "id" | "de" | "ja";

export interface Product {
  id: number;
  slug: string;
  image: string;
  gallery: string[];
  videoUrl?: string;
  nameKey: string;
  descKey: string;
  longDescKey: string;
  metaTitleKey: string;
  metaDescKey: string;
  metaKeywordsKey: string;
  price: string;
  badge?: string;
  comingSoon?: boolean;
}

export interface Translations {
  ageTitle: string;
  ageSubtitle: string;
  ageLabel: string;
  agePlaceholder: string;
  ageButton: string;
  ageError: string;
  ageUnder: string;
  navProducts: string;
  navContact: string;
  heroTitle: string;
  heroSubtitle: string;
  heroButton: string;
  productsTitle: string;
  productsSubtitle: string;
  viewDetails: string;
  contactTitle: string;
  contactSubtitle: string;
  contactName: string;
  contactEmail: string;
  contactMessage: string;
  contactSend: string;
  contactSuccess: string;
  contactPhone: string;
  contactTelegram: string;
  contactWhatsapp: string;
  footerText: string;
  close: string;
  gallery: string;
  video: string;
  product1Name: string;
  product1Desc: string;
  product1Long: string;
  product2Name: string;
  product2Desc: string;
  product2Long: string;
  product3Name: string;
  product3Desc: string;
  product3Long: string;
  priceOnRequest: string;
  comingSoon: string;
  product1MetaTitle: string;
  product1MetaDesc: string;
  product1MetaKeywords: string;
  product2MetaTitle: string;
  product2MetaDesc: string;
  product2MetaKeywords: string;
  product3MetaTitle: string;
  product3MetaDesc: string;
  product3MetaKeywords: string;
}